---
title: ""
output: html_document
---
  
  
__Title__: Clinical and Laboratory Predictors of Stroke Associated with COVID-19 Disease  
   
__Authors__: Valerie Bromberg; Leigh Cressman, MS; Pam Tolomeo, MPH; Hatem O. Abdallah, MD; Alexis Holmes, MD; Jay Garcia, MD; Ashini Patel; Matthew J. Ziegler, MD, MSCE; Jackie Omorogbe; Keith Hamilton, MD; Ebbing Lautenbach, MD, MPH, MSCE; Michael Z. David, MD, PhD; Brendan J. Kelly, MD, MS for the CDC Prevention Epicenters    
   
__Background__: Although SARS-CoV-2 predominantly targets the respiratory system, it has also been associated with vascular complications including stroke. Identifying COVID-19 patients at elevated risk for stroke can help inform target anticoagulation strategies. We sought to understand how symptoms and laboratory markers at presentation with COVID-19 relate to stroke risk.   
  
__Methods__: We enrolled a cohort of 1324 subjects who were hospitalized with COVID-19 across six PennMedicine hospitals between April and August 2020 and performed retrospective, manual chart review to measure exposures including presenting symptoms and admission inflammatory markers. Data were organized with a REDCap database, and analyses were performed using R statistical software, with Bayesian binomial regression models fit using Stan Hamiltonian Monte Carlo via the "brms" package.  
  
__Results__: Among 1324 subjects, 19 stroke events were observed within 30 days of COVID-19 diagnosis. Admission inflammatory markers, including C-reactive protein (CRP), erythrocyte sedimentation rate (ESR), ferritin, and D-dimer, were poor predictors of stroke risk. Among presenting symptoms, including respiratory, gastrointestinal, dermatologic, and neurologic features of COVID-19 disease, only altered mental status documented on presentation was significantly associated with stroke risk (odds ratio 6.06, 95% credible interval 2.16 - 18.7).   
  
__Discussion__: Inflammatory markers associated with COVID-19 disease severity did not discriminate patients at high versus low risk of stroke in this cohort. Altered mental status documented on presentation was significantly associated with incident stroke during COVID-19 disease.    
  
  
  
  
  